language: node_js
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy.key
- ssh-add .travis/deploy.key
- ssh-keyscan 13.229.127.254 >> ~/.ssh/known_hosts
- git remote add deploy dokku@13.229.127.254:sample-node-app
- git config --global push.default simple
- git push deploy master
before_install:
- openssl aes-256-cbc -K $encrypted_ed4fc6007ffa_key -iv $encrypted_ed4fc6007ffa_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
